permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: Design Mind
  description: |
    A Graphic Design Search Web App
  font_url: "https://fonts.googleapis.com/css?family=Libre+Baskerville|Montserrat:400,500,700&display=swap"
  layouts:
    default: |
      sadfas
  colors:
    background: "--color-background"
    accent: "--color-primary"
    patterns:
      brand.logos: "--color-secondary"
  rationales:
    typefaces.primary: |
      It is a clean sans serif that looks professional and easy to read
    colors.primary: |
      Is calm, professional, and looks reliable
    colors.secondary: |
      Complementary colour to primary colour and stands out as for call to actions
    colors.additional: |
      accents of the primary colour allow us to create heirarchy through colour
# collections:
#     products:
#         output: true
# defaults:
#   - scope:
#       path:
#     values:
#       layout:
