title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  buttons:
    fields:
      - name: text
        type: string
        example: "See Results"
      - name: url
        type: url
        example: "/index/"
    width: "12em"
