title: "Cards"
description: |
  This is where you can find card layouts designed for different content

patterns:
  contact-cards:
    title: "Contact Cards"
    description: |
      Use this type of card to display information about the designer or agency
    fields:
      - name: name
        type: string
        example: "Qoncept Studio"
      - name: company-description
        type: string
        example: "Print Designers - UI Designers"
      - name: from
        type: string
        example: "Ottawa, Ontario"
      - name: since
        type: string
        example: "September 2019"
      - name: response
        type: string
        example: "12 hours"
      - name: recent
        type: string
        example: "Branding - 4 days ago"
      - name: image
        type: url
        example: "/images/3by2.png"
      - name: aria-details
        type: string
        example: "Assign non-visible text to enhance the description of an element"
      - name: aria-label
        type: string
        example: "Assign the description of an element to other elements on the page"
      - name: alt-text
        type: string
        example: "Assign the description to an image if necessary"

  description:
    title: "Detail Headers"
    description: |
      Use when wanting to showcase interesting point.
    fields:
      - name: header
        type: string
        example: "Why People Like Us"
      - name: subheader
        type: string
        example: "Designer Focused"
      - name: description
        type: string
        example: "No undercutting, no bidding for projects, no spec work."
    width: "40em"
