title: "Cards"
description: |
  The form can be used when creating a product description. Use corresponding icon with product description

patterns:
  figure:
    title: "figure with caption"
    description: |
      Use this type of card for products
    fields:
      - name: name
        type: string
        example: "Figure header"
      - name: company-description
        type: string
        example: "Qoncept Studio"
      - name: from
        type: string
        example: "Print Designers - UI Designers"
      - name: since
        type: string
        example: "September 2019"
      - name: response
        type: string
        example: "12 hours"
      - name: recent
        type: string
        example: "Branding - 4 days ago"
      - name: image
        type: url
        example: "/images/placeholder-1by1.svg"
      - name: aria-details
        type: string
        example: "Assign non-visible text to enhance the description of an element"
      - name: aria-label
        type: string
        example: "Assign the description of an element to other elements on the page"
      - name: alt-text
        type: string
        example: "Assign the description to an image if necessary"
    width: "20em"
